### ISSUE TITLE
add azure-identity to conda-forge

### ISSUE THREAD

**Issue by raybellwaves** [conda-forge/adlfs-feedstock#4]
azure-identity is a required dependency

**Comment by raybellwaves** [comment]
@marcelotrevisani don't suppose you have any interest on adding azure-identity to conda-forge?
https://pypi.org/project/azure-identity/
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/setup.py#L43

Not sure if it an easy adaption of https://github.com/conda-forge/azure-core-feedstock/blob/master/recipe/meta.yaml?

**Comment by marcelotrevisani** [comment]
Related to https://github.com/conda-forge/staged-recipes/pull/12293

If you want to, you can also add new packages to ``conda-forge``. Just follow the guidelines and add a new PR in
https://github.com/conda-forge/staged-recipes

For packages on ``pypi`` you can use [grayskull](https://github.com/marcelotrevisani/grayskull) to generate a recipe for you.  :)

**Comment by raybellwaves** [comment]
thanks @marcelotrevisani
